name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js (optional, only if needed for builds)
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 🔐 Create config.json with your secret
      - name: Create config.json
        run: |
          echo '{ "GOOGLE_MAPS_API_KEY": "${{ secrets.GOOGLE_MAPS_API_KEY }}" }' > config.json

      # 📤 Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Adjust if your site files are in a subfolder like dist/
